class ResponseForPMS {
  final String message;
  final bool error;
  final List<Data> data;

  ResponseForPMS(this.message, this.error, this.data);

  ResponseForPMS.fromJson(Map jsonMap)
      : message = jsonMap['message'],
        error = jsonMap['error'],
        data = jsonMap['data'];
}

class Data {
  String? orderid,
      serial_no,
      id_no,
      order_num,
      order_date,
      job_num,
      release_date,
      territory_id,
      sales_rep_code,
      customer_name,
      customer_contact_name,
      city,
      state,
      phone_num,
      mobile_num,
      email_address,
      customer_type,
      billing_group,
      project,
      date_12,
      prc_con_num,
      part_num,
      line_desc,
      order_qty,
      doc_unit_price,
      doc_total_discount,
      doc_order_amt,
      need_by_date,
      request_date,
      date_06,
      reference,
      short_char_05,
      terms_code,
      character_08,
      short_char_01;

  Data(
      this.orderid,
      this.serial_no,
      this.id_no,
      this.order_num,
      this.order_date,
      this.job_num,
      this.release_date,
      this.territory_id,
      this.sales_rep_code,
      this.customer_name,
      this.customer_contact_name,
      this.city,
      this.state,
      this.phone_num,
      this.mobile_num,
      this.email_address,
      this.customer_type,
      this.billing_group,
      this.project,
      this.date_12,
      this.prc_con_num,
      this.part_num,
      this.line_desc,
      this.order_qty,
      this.doc_unit_price,
      this.doc_total_discount,
      this.doc_order_amt,
      this.need_by_date,
      this.request_date,
      this.date_06,
      this.reference,
      this.short_char_05,
      this.terms_code,
      this.character_08,
      this.short_char_01);

  Data.fromJson(Map jsonMap)
      : orderid = jsonMap['orderid'],
        serial_no = jsonMap['serial_no'],
        id_no = jsonMap['id_no'],
        order_num = jsonMap['order_num'],
        order_date = jsonMap['order_date'],
        job_num = jsonMap['job_num'],
        release_date = jsonMap['release_date'],
        territory_id = jsonMap['territory_id'],
        sales_rep_code = jsonMap['sales_rep_code'],
        customer_name = jsonMap['customer_name'],
        customer_contact_name = jsonMap['customer_contact_name'],
        city = jsonMap['city'],
        state = jsonMap['state'],
        phone_num = jsonMap['phone_num'],
        mobile_num = jsonMap['mobile_num'],
        email_address = jsonMap['email_address'],
        customer_type = jsonMap['customer_type'],
        billing_group = jsonMap['billing_group'],
        project = jsonMap['project'],
        date_12 = jsonMap['date_12'],
        prc_con_num = jsonMap['prc_con_num'],
        part_num = jsonMap['part_num'],
        line_desc = jsonMap['line_desc'],
        order_qty = jsonMap['order_qty'],
        doc_unit_price = jsonMap['doc_unit_price'],
        doc_total_discount = jsonMap['doc_total_discount'],
        doc_order_amt = jsonMap['doc_order_amt'],
        need_by_date = jsonMap['need_by_date'],
        request_date = jsonMap['request_date'],
        date_06 = jsonMap['date_06'],
        reference = jsonMap['reference'],
        short_char_05 = jsonMap['short_char_05'],
        terms_code = jsonMap['terms_code'],
        character_08 = jsonMap['character_08'],
        short_char_01 = jsonMap['short_char_01'];
}
